Models/Carrinho.cs
using System;
using Microsoft.EntityFrameworkCore;
using TaskOrder.Context;

namespace TaskOrder.Models
{
    public class Carrinho
    {
        private readonly AppDbContext _context;
        public Carrinho(AppDbContext context)
        {
            _context = context;
        }

        public string CarrinhoId { get; set; }
        public List<CarrinhoItem> CarrinhoItens { get; set; }
        public static Carrinho GetCarrinhoCompra(IServiceProvider
        services)
        {

            ISession session =

            services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;

            var context = services.GetService<AppDbContext>();
            string carrinhoId = session.GetString("CarrinhoId") ??

            Guid.NewGuid().ToString();

            session.SetString("CarrinhoId", carrinhoId);
            return new Carrinho(context)
            {
                CarrinhoId = carrinhoId
            };

        }
        public void AdicionarItemCarrinho(Item item)
        {
            var carinhoItem = _context.CarrinhoItens.SingleOrDefault(s => s.Item.ItemId == item.ItemId && s.CarrinhoId == CarrinhoId);

            if (carinhoItem == null)
            {
                carinhoItem = new CarrinhoItem
                {
                    CarrinhoId = CarrinhoId,
                    Item = item,
                    Quantidade = 1
                };
                _context.CarrinhoItens.Add(carinhoItem);
            }
            else
            {
                carinhoItem.Quantidade++;
            }
            _context.SaveChanges();
        }
        public int RemoverItemDoCarrinhoCompra(Item item)
        {
            var carrinhoQuantidade = 0;
            var carinhoItem = _context.CarrinhoItens.SingleOrDefault(s =>

            s.Item.ItemId == item.ItemId && s.CarrinhoId == CarrinhoId);

            if (carinhoItem != null)
            {
                if (carinhoItem.Quantidade > 1)
                {
                    carinhoItem.Quantidade--;
                    carrinhoQuantidade = carinhoItem.Quantidade;
                }
                else
                {
                    _context.CarrinhoItens.Remove(carinhoItem);
                }

            }
            _context.SaveChanges();
            return carrinhoQuantidade;
        }
        public List<CarrinhoItem> GetCarrinhoCompraItems()
        {
            return CarrinhoItens ?? _context.CarrinhoItens.Where(c =>

            c.CarrinhoId == CarrinhoId).Include(s => s.Item).ToList();
        }
        public void LimparCarrinho()
        {
            var carrinhoCompra = _context.CarrinhoItens.Where(c => c.CarrinhoId == CarrinhoId);

            _context.CarrinhoItens.RemoveRange(carrinhoCompra);
            _context.SaveChanges();
        }
        public double GetCarrinhoCompraTotal()
        {
            List<double> total = _context.CarrinhoItens.Where(_c =>

            _c.CarrinhoId == CarrinhoId).Select(c =>
            c.Quantidade * c.Item.Preco).ToList();
            double totalr = 0;
            foreach (double t in total)
            {
                totalr = totalr + t;
            }
            return totalr;
        }
    }
}

Controllers/CarrinhoController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TaskOrder.Models;
using TaskOrder.Repositories.Interfaces;
using TaskOrder.ViewModel;

namespace TaskOrder.Controllers
{
    [Authorize]
    public class CarrinhoController : Controller
    {
        private readonly Carrinho _carrinho;
        private readonly IItemRepository _itemRepository;
        public CarrinhoController(Carrinho carrinho, IItemRepository itemRepository)
        {
            _carrinho = carrinho;
            _itemRepository = itemRepository;
        }
        public IActionResult Index()
        {
            var itens = _carrinho.GetCarrinhoCompraItems();
            _carrinho.CarrinhoItens = itens;
            var carrinhoVM = new CarrinhoViewModel
            {
                Carrinho = _carrinho,
                CarrinhoTotal = _carrinho.GetCarrinhoCompraTotal()
            };
            return View(carrinhoVM);
        }
        public IActionResult AdicionarItemNoCarrinhoCompra(int itemId)
        {
            var itemSelecionado = _itemRepository.Itens.FirstOrDefault(l => l.ItemId == itemId);
            if (itemSelecionado != null)
            {
                _carrinho.AdicionarItemCarrinho(itemSelecionado);
            }
            return RedirectToAction("Index");
        }
        public IActionResult RemoverCarrinho(int itemId)
        {
            var itemSelecionado = _itemRepository.Itens.FirstOrDefault(l => l.ItemId == itemId);
            if (itemSelecionado != null)
            {
                _carrinho.RemoverItemDoCarrinhoCompra(itemSelecionado);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/ItemController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using TaskOrder.Models;
using TaskOrder.Repositories.Interfaces;
using TaskOrder.ViewModel;

namespace TaskOrder.Controllers
{
    public class ItemController : Controller
    {
        private readonly IItemRepository _itemRespository;
        public ItemController(IItemRepository itemRespository)
        {
            _itemRespository = itemRespository;
        }
        public IActionResult List(string categoria)
        {
            IEnumerable<Item> itens;
            var categoriaAtual = string.Empty;
            if (string.IsNullOrEmpty(categoria))
            {
                itens = _itemRespository.Itens.OrderBy(m => m.ItemId);
                categoriaAtual = "Todos os itens";
            }
            else
            {
                itens = _itemRespository.Itens.Where(m =>
                m.Categoria.Nome.Equals(categoria)).OrderBy(m => m.ItemId);

                categoriaAtual = categoria;
            }
            var ItemListViewItem = new ItemListViewModel
            {
                Itens = itens,
                CategoriaAtual = categoriaAtual
            };
            return View(ItemListViewItem);
        }

        public IActionResult Details(int itemId)
        {

            var movel = _itemRespository.Itens.FirstOrDefault(m =>

            m.ItemId == itemId);

            return View(movel);
        }
        public IActionResult Search(string searchString)
        {

            IEnumerable<Item> itens;
            string categoriaAtual = string.Empty;
            if (string.IsNullOrEmpty(searchString))
            {
                itens = _itemRespository.Itens.OrderBy(m => m.Nome);
                categoriaAtual = "Todos os Itens";
            }
            else
            {
                itens = _itemRespository.Itens.Where(m =>
                m.Nome.ToLower() == searchString.ToLower()).OrderBy(m => m.Nome);

                if (itens.Any())
                {
                    categoriaAtual = "Itens";
                }
                else
                {
                    categoriaAtual = "Nada encontrado";
                }
            }
            return View("~/Views/Item/List.cshtml", new
            ItemListViewModel
            {
                CategoriaAtual = categoriaAtual,
                Itens = itens
            });

        }
    }

}

Controllers/PedidoController.cs
using TaskOrder.Models;
using TaskOrder.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
namespace TaskOrder.Controllers
{
    [Authorize]
    public class PedidoController : Controller
    {
        private readonly IPedidoRepository _pedidoR;
        private readonly Carrinho _carrinho;
        public PedidoController(IPedidoRepository pedidoR, Carrinho carrinho)
        {
            _pedidoR = pedidoR;
            _carrinho = carrinho;
        }
        public IActionResult Checkout()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Checkout(Pedido pedido)
        {
            int totalItensPedido = 0;
            decimal precoTotalPedido = 0.0m;
            //obtem os itens do carrinho de compra do cliente
            List<CarrinhoItem> items = _carrinho.GetCarrinhoCompraItems();
            _carrinho.CarrinhoItens = items;
            //verifica se existem itens de pedido
            if (_carrinho.CarrinhoItens.Count == 0)
            {
                ModelState.AddModelError("", "Seu carrinho esta vazio, que tal incluir um lanche...");
            }
            //calcula o total de itens e o total do pedido
            foreach (var item in items)
            {
                totalItensPedido += item.Quantidade;
                precoTotalPedido += (Convert.ToDecimal(item.Item.Preco) * item.Quantidade);
            }
            //atribui os valores obtidos ao pedido
            pedido.TotalItensPedido = totalItensPedido;
            pedido.PedidoTotal = precoTotalPedido;
            //valida os dados do pedido
            if (ModelState.IsValid)
            {
                //cria o pedido e os detalhes
                _pedidoR.CriarPedido(pedido);
                //define mensagens ao cliente
                ViewBag.CheckoutCompletoMensagem = "Obrigado pelo seu pedido :)";
                ViewBag.TotalPedido = _carrinho.GetCarrinhoCompraTotal();
                //limpa o carrinho do cliente
                _carrinho.LimparCarrinho();
                //exibe a view com dados do cliente e do pedido
                return View("~/Views/Pedido/CheckoutCompleto.cshtml", pedido);
            }
            return View(pedido);
        }
    }
}

Views/Carrinho/Index.cshtml
@model CarrinhoViewModel
<div class="Container">
    <div class="row checkoutForm">
        <div class="">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                class="bi bi-basket2-fill" viewBox="0 0 16 16">
                <path
                    d="M5.929 1.757a.5.5 0 1 0-.858-.514L2.217 6H.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h.623l1.844 6.456A.75.75 0 0 0 3.69 15h8.622a.75.75 0 0 0 .722-.544L14.877 8h.623a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1.717L10.93 1.243a.5.5 0 1 0-.858.514L12.617 6H3.383L5.93 1.757zM4 10a1 1 0 0 1 2 0v2a1 1 0 1 1-2 0v-2zm3 0a1 1 0 0 1 2 0v2a1 1 0 1 1-2 0v-2zm4-1a1 1 0 0 1 1 1v2a1 1 0 1 1-2 0v-2a1 1 0 0 1 1-1z" />
            </svg>
            <h4>Seu carrinho de compras: </h4>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Quantidade</th>
                    <th>Item</th>
                    <th class="text-right">Preço</th>
                    <th class="text-right">Subtotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Carrinho.CarrinhoItens)
                {
                    <tr>
                        <td class="text-center">@item.Quantidade</td>
                        <td class="text-left">@item.Item.Nome</td>
                        <td class="text-right">@item.Item.Preco.ToString("c")</td>
                        <td class="text-right">
                            @((item.Quantidade * item.Item.Preco).ToString("c"))
                        </td>
                        <td class="text-center">
                            <a asp-controller="Carrinho" asp-action="RemoverCarrinho"
                                asp-route-itemId="@item.Item.ItemId"><svg xmlns="http://www.w3.org/2000/svg" width="16"
                                    height="16" fill="currentColor" class="bi bi-x-circle text-danger" viewBox="0 0 16 16">
                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                    <path
                                        d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                                </svg>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-right">Total:</td>
                    <td class="text-right">
                        @Model.CarrinhoTotal.ToString("c")
                    </td>
                </tr>
            </tfoot>
        </table>

        <div class="text-right">
            <div class="btn-group">
                <a class="btn rounded-3 btn-danger" asp-controller="Pedido" asp-action="Checkout">Encerrar
                    Pedido</a>

                &nbsp;&nbsp;&nbsp;
                <a class="btn rounded-3 btn-warning" asp-controller="Item" asp-action="List">Continuar
                    Comprando</a>
            </div>
        </div>
        <br />
    </div>
</div>